# Generated by Django 2.2.28 on 2025-03-09 23:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inqpal', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='friends',
            field=models.ManyToManyField(blank=True, related_name='watchers', to='inqpal.Account'),
        ),
        migrations.AlterField(
            model_name='post',
            name='roars',
            field=models.ManyToManyField(blank=True, related_name='roared_posts', to='inqpal.Account'),
        ),
    ]
