# Generated by Django 2.2.28 on 2025-03-13 15:18

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inqpal', '0002_auto_20250309_2343'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2025, 1, 1, 0, 0)),
        ),
        migrations.AddField(
            model_name='post',
            name='date',
            field=models.DateField(default=datetime.datetime(2025, 1, 1, 0, 0)),
        ),
    ]
