# Generated by Django 2.2.28 on 2025-03-13 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inqpal', '0003_auto_20250313_1518'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='picture',
            field=models.ImageField(blank=True, default='default.jpg', upload_to='profile_images'),
        ),
    ]
