# Generated by Django 2.2.28 on 2025-03-20 02:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inqpal', '0003_auto_20250313_1518'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('description', models.CharField(max_length=1000)),
                ('picture', models.ImageField(upload_to='category_images')),
            ],
        ),
        migrations.AlterField(
            model_name='account',
            name='picture',
            field=models.ImageField(blank=True, default='noImageSelected.png', upload_to='profile_images'),
        ),
        migrations.AlterField(
            model_name='post',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inqpal.Category'),
        ),
        migrations.AlterField(
            model_name='post',
            name='text',
            field=models.CharField(max_length=1000),
        ),
    ]
