# Generated by Django 2.2.28 on 2025-03-20 16:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inqpal', '0004_auto_20250313_2134'),
        ('inqpal', '0004_auto_20250320_0230'),
    ]

    operations = [
    ]
