# Generated by Django 2.2.28 on 2025-03-20 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inqpal', '0005_merge_20250320_1635'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='picture',
            field=models.ImageField(blank=True, default='noImageSelected.png', upload_to='profile_images'),
        ),
    ]
